#!/usr/bin/env bash

echo "------------------------------------------------------------"
echo -n "User    : "
whoami
echo -n "Hostname: "
hostname
echo -n "Host IP : "
hostname -i
echo -n "Uptime  : "
uptime -p
echo -n "Kernel  : "
uname -rms
echo "------------------------------------------------------------"
